import { MenuAdmin } from '../../interfaces/menu-admin';

export const menuItemsAdmin: MenuAdmin[] = [
  // Parent Dashboard
  {
    id: '1',
    title: 'Dashboard',
    icon: 'dashboard',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard',
    href: null,
    target: null,
  },
  // Parent Customization
  {
    id: '2',
    title: 'Customization',
    icon: 'dashboard_customize',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '2a',
    title: 'Main Menu',
    icon: 'category',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'main-menu',
    href: null,
    target: null,
  },
  {
    id: '2c',
    title: 'Carousel',
    icon: 'category',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'customization/primary-carousel',
    href: null,
    target: null,
  },
  {
    id: '2d',
    title: 'Contact Info',
    icon: 'category',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'customization/contact-info',
    href: null,
    target: null,
  },
  {
    id: '2f',
    title: 'Branch Info',
    icon: 'category',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'customization/branch',
    href: null,
    target: null,
  },

  // Parent All Pages
  {
    id: '3',
    title: 'All Pages',
    icon: 'card_giftcard',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'pages-info',
    href: null,
    target: null,
  },

  // Parent Products
  {
    id: '4',
    title: 'Categories',
    icon: 'category',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '4d',
    title: 'Brands',
    icon: 'loyalty',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'products/authors',
    href: null,
    target: null,
  },
  {
    id: '4d',
    title: 'Categories',
    icon: 'category',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'products/categories',
    href: null,
    target: null,
  },
  {
    id: '4f',
    title: 'Sub Categories',
    icon: 'loyalty',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'products/sub-categories',
    href: null,
    target: null,
  },
  {
    id: '4e',
    title: 'Featured Categories',
    icon: 'loyalty',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'products/featured-categories',
    href: null,
    target: null,
  },
  // Parent Products
  {
    id: '5',
    title: 'Products',
    icon: 'view_list',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '5a',
    title: 'Products List',
    icon: 'list',
    hasSubMenu: false,
    parentId: '5',
    routerLink: 'products/product-list',
    href: null,
    target: null,
  },
  {
    id: '5b',
    title: 'Add Product',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '5',
    routerLink: 'products/add-product',
    href: null,
    target: null,
  },
  // Parent Offer
  {
    id: '6',
    title: 'Offers',
    icon: 'local_offer',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '6a',
    title: 'Offer Banner',
    icon: 'category',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'customization/offer-banner',
    href: null,
    target: null,
  },
  {
    id: '6b',
    title: 'Offer Tabs',
    icon: 'category',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'customization/offer-tabs',
    href: null,
    target: null,
  },
  {
    id: '6c',
    title: 'Offer Product',
    icon: 'remove_red_eye',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'products/offer-product',
    href: null,
    target: null,
  },
  {
    id: '74RZ',
    title: 'Featured Product',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'featured-product',
    href: null,
    target: null,
  },
  {
    id: '6d',
    title: 'Offer Package',
    icon: 'remove_red_eye',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'products/offer-package',
    href: null,
    target: null,
  },
  {
    id: '6d',
    title: 'Coupons',
    icon: 'card_giftcard',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'coupons',
    href: null,
    target: null,
  },
  {
    id: '6e',
    title: 'Offer Category Card',
    icon: 'savings',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'offer-category-card',
    href: null,
    target: null,
  },
  {
    id: 'Opf5a',
    title: 'Campaign',
    icon: 'list',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'promotional-offer',
    href: null,
    target: null,
  },
  {
    id: 'Opf5b',
    title: 'Campaign Product',
    icon: 'list',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'promotional-offer-product',
    href: null,
    target: null,
  },

  // {
  //   id: 'of31',
  //   title: 'Offers',
  //   icon: 'view_list',
  //   hasSubMenu: true,
  //   parentId: null,
  //   routerLink: null,
  //   href: null,
  //   target: null
  // },

  // Parent Gallery Folder
  {
    id: '731',
    title: 'Gallery',
    icon: 'collections',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '45x',
    title: 'Image Folder',
    icon: 'folder',
    hasSubMenu: false,
    parentId: '731',
    routerLink: 'image-folder',
    href: null,
    target: null,
  },
  // Parent Gallery
  {
    id: '4',
    title: 'Image Gallery',
    icon: 'collections',
    hasSubMenu: false,
    parentId: '731',
    routerLink: 'image-gallery',
    href: null,
    target: null,
  },

  // Parent Sells
  {
    id: '7',
    title: 'Sales',
    icon: 'monetization_on',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '7a',
    title: 'Orders',
    icon: 'list_alt',
    hasSubMenu: false,
    parentId: '7',
    routerLink: 'sales/orders',
    href: null,
    target: null,
  },
  {
    id: '7b',
    title: 'Transactions',
    icon: 'local_atm',
    hasSubMenu: false,
    parentId: '7',
    routerLink: 'sales/transactions',
    href: null,
    target: null,
  },
  {
    id: '7b',
    title: 'Shipping Charge',
    icon: 'insert_comment',
    hasSubMenu: false,
    parentId: '7',
    routerLink: 'shipping-charge',
    href: null,
    target: null,
  },
  // parent Admin Control
  {
    id: '9',
    title: 'Admin Control',
    icon: 'offline_bolt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '9a',
    title: 'Roles',
    icon: 'insert_comment',
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'roles',
    href: null,
    target: null,
  },
  // Parent Users
  {
    id: '9b',
    title: 'Users',
    icon: 'group_add',
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'users',
    href: null,
    target: null,
  },
  // Parent Customers
  {
    id: '10',
    title: 'Customers',
    icon: 'supervisor_account',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'customers',
    href: null,
    target: null,
  },
  {
    id: '13',
    title: 'Reviews',
    icon: 'insert_comment',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'reviews',
    href: null,
    target: null,
  },
  {
    id: 'bac2021',
    title: 'Backup & Restore',
    icon: 'warning',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'backup-restore',
    href: null,
    target: null,
  },
  // Parent Support
  {
    id: '14',
    title: 'Support',
    icon: 'support_agent',
    hasSubMenu: false,
    parentId: null,
    routerLink: null,
    href: 'https://softlabit.com/',
    target: '_blank',
  },
];
