import {SidenavMenu} from '../../../interfaces/sidenav-menu';


export const sidenavMenuItems: SidenavMenu[] = [
  {id: '1', title: 'Home', routerLink: '/', href: null, hasSubMenu: false, parentId: '0'},
  {id: '2', title: 'Fashion', routerLink: null, href: null, hasSubMenu: false, parentId: '0'},
  {id: '10', title: 'Women', routerLink: null, href: null, hasSubMenu: false, parentId: '2'},
  {id: '11', title: 'Dresses & Skirts', routerLink: '/products/dresses & skirts', href: null, hasSubMenu: false, parentId: '10'},
  {id: '12', title: 'Jackets', routerLink: '/products/jackets', href: null, hasSubMenu: false, parentId: '10'},
  {id: '13', title: 'Tops & Blouses', routerLink: '/products/shoes & boots', href: null, hasSubMenu: false, parentId: '10'},
  {id: '14', title: 'Knitwear', routerLink: '/products/knitwear', href: null, hasSubMenu: false, parentId: '10'},
  {id: '15', title: 'Men', routerLink: '/products/men', href: null, hasSubMenu: false, parentId: '2'},
  {id: '20', title: 'T-shirts & Polos', routerLink: '/products/t-shirts & polos', href: null, hasSubMenu: false, parentId: '20'},
  {id: '21', title: 'Shoe & Boots', routerLink: '/products/shoe & boots', href: null, hasSubMenu: false, parentId: '20'},
  {id: '22', title: 'Jeans', routerLink: '/products/jeans', href: null, hasSubMenu: false, parentId: '20'},
  {id: '23', title: 'Coats', routerLink: '/products/coats', href: null, hasSubMenu: false, parentId: '20'},
  {id: '24', title: 'Kids', routerLink: null, href: null, hasSubMenu: false, parentId: '2'},
  {id: '30', title: 'Top', routerLink: '/products/top', href: null, hasSubMenu: false, parentId: '2'},
  {id: '32', title: 'Pants & Shorts', routerLink: '/products/pants & shorts', href: null, hasSubMenu: false, parentId: '30'},
  {id: '33', title: 'Dresses', routerLink: '/products/dresses', href: null, hasSubMenu: false, parentId: '30'},
  {id: '34', title: 'Skirts', routerLink: '/products/skirts', href: null, hasSubMenu: false, parentId: '30'},
  {id: '35', title: 'Set & Body', routerLink: '/products/set & body', href: null, hasSubMenu: false, parentId: '30'},
  {id: '40', title: 'Accessories', routerLink: null, href: null, hasSubMenu: true, parentId: '2'},
  {id: '41', title: 'Watches', routerLink: '/products/watches', href: null, hasSubMenu: false, parentId: '40'},
  {id: '42', title: 'Bags & Wallet', routerLink: '/products/bags & wallet', href: null, hasSubMenu: false, parentId: '40'},
  {id: '43', title: 'Sunglasses', routerLink: '/products/sunglasses', href: null, hasSubMenu: false, parentId: '40'},
  {id: '44', title: 'Belts & Hats', routerLink: '/products/belts & hats', href: null, hasSubMenu: false, parentId: '40'},
  {id: '50', title: 'Jewellery', routerLink: '/products/jewellery', href: null, hasSubMenu: false, parentId: '0'},
  {id: '51', title: 'Electronics', routerLink: '/products/electronics', href: null, hasSubMenu: false, parentId: '0'},
  {id: '52', title: 'Sports', routerLink: '/products/sports', href: null, hasSubMenu: false, parentId: '0'},
  {id: '60', title: 'Pages', routerLink: null, href: null, hasSubMenu: true, parentId: '0'},
  {id: '61', title: 'All products', routerLink: '/products', href: null, hasSubMenu: false, parentId: '60'},
  {id: '62', title: 'Product detail', routerLink: '/products/2/PC All-in-One', href: null, hasSubMenu: false, parentId: '60'},
  {id: '63', title: 'Sign in', routerLink: '/sign-in', href: null, hasSubMenu: false, parentId: '60'},
  {id: '64', title: '404 Error', routerLink: '/404', href: null, hasSubMenu: false, parentId: '60'},
  {id: '65', title: 'Landing', routerLink: '/landing', href: null, hasSubMenu: false, parentId: '60'},
  {id: '80', title: 'Contact', routerLink: '/contact', href: null, hasSubMenu: false, parentId: '0'},
  {id: '90', title: 'Admin Panel', routerLink: '/admin', href: null, hasSubMenu: false, parentId: '0'},
  {id: '140', title: 'Level 1', routerLink: null, href: null, hasSubMenu: true, parentId: '0'},
  {id: '141', title: 'Level 2', routerLink: null, href: null, hasSubMenu: true, parentId: '140'},
  {id: '142', title: 'Level 3', routerLink: null, href: null, hasSubMenu: true, parentId: '141'},
  {id: '143', title: 'Level 4', routerLink: null, href: null, hasSubMenu: true, parentId: '142'},
  {id: '144', title: 'Level 5', routerLink: null, href: 'http://themeseason.com', hasSubMenu: false, parentId: '143'},
  {id: '200', title: 'External Link', routerLink: null, href: 'http://themeseason.com', hasSubMenu: false, parentId: '0'}
];

